# WHAT ARE KEYWORDS IN PYTHON

'''

KEYWORDS ARE RESERVED WORDS WHICH ARE USE AS IDENTIFIER FUNCTION NAME

THE HELP DEFINE THE STRUCTURE AND SYNTAX OF THE LANGUAGE

THEE ARE 33 KEYWORDS IN PYTHON

KEYWORDS: FALSE,NONE , TRUE, INT

'''
